version: 2.1

jobs:
  # build:
  #   docker:
  #     - image: circleci/node:14 # Use Node.js 14
  #   steps:
  #     - checkout # Check out the code
  #     - run:
  #         name: Install Dependencies
  #         command: npm install # Install dependencies, including devDependencies

  build_and_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install # Ensure dependencies are installed
      - run:
          name: Run Tests
          command: npm run test # Run Mocha using npx to ensure local execution

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Deploy to Production Server
          # command: echo "Deploying to production server" # Replace with your actual deployment command
          command: npm start # Run Node server

workflows:
  version: 2
  workFlowName_test:
    jobs:
      # - build
      - build_and_test
        # requires:
        #   - build
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
