version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Use the desired Node.js version
    steps:
      - checkout # Checkout the code from the repository
      - run:
          name: Install Dependencies
          command: npm install

  tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test # This should execute your tests using Mocha

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Deploy to Production Server
          command: echo "Deploying to production server" # Replace with actual deployment command

workflows:
  workFlowName_test:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
          filters:
            branches:
              only: main
